version: '3'

services:
    composer:
        build:
            args:
                composer_dev_arg: --no-dev
    composer-dev:
        build:
            context: .
            dockerfile: Dockerfile.composer
            args:
                composer_dev_arg:
        image: elifesciences/recommendations_composer_dev:${IMAGE_TAG}
        command: /bin/bash
    ci:
        build:
            context: .
            dockerfile: Dockerfile.ci
            args:
                image_tag: ${IMAGE_TAG}
        image: elifesciences/recommendations_ci:${IMAGE_TAG}
        environment:
            - APP_ENV=ci
        depends_on:
            - composer-dev
            - fpm
