services:
    ci:
        build:
            context: .
            dockerfile: Dockerfile
            target: ci
        image: elifesciences/recommendations_ci:${IMAGE_TAG}
        environment:
            - APP_ENV=ci
