version: '3'

services:
    composer:
        build:
            context: .
            dockerfile: Dockerfile
            target: composer
            args:
                php_version: ${PHP_VERSION}
        command: /bin/bash
        volumes:
            - ./composer.json:/app/composer.json
            - ./composer.lock:/app/composer.lock
            - vendor:/app/vendor
    fpm:
        volumes:
            - ./:/srv/recommendations
            - /srv/recommendations/build
            - /srv/recommendations/var
            - .docker/config.php:/srv/recommendations/config.php
            - vendor:/srv/recommendations/vendor
        environment:
            - APP_ENV=${APP_ENV}
        depends_on:
            - composer
volumes:
    vendor:
