version: '3.4'

services:
    ci:
        build:
            context: .
            dockerfile: Dockerfile
            target: ci
            args:
                php_version: ${PHP_VERSION}
        image: elifesciences/recommendations_ci:${IMAGE_TAG}
        environment:
            - APP_ENV=ci
