version: '3'

services:
    composer:
        build:
            context: .
            dockerfile: Dockerfile.composer
            args:
                composer_dev_arg: ${COMPOSER_DEV_ARG}
        image: elifesciences/recommendations_composer:${IMAGE_TAG}
        command: /bin/bash
    fpm:
        build:
            context: .
            args:
                image_tag: ${IMAGE_TAG}
                php_version: ${PHP_VERSION}
        image: elifesciences/recommendations:${IMAGE_TAG}
        depends_on:
            - composer
            - api_dummy
    web:
        image: nginx:1.13.12-alpine
        volumes:
            - ./.docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8080:80'
        depends_on:
            - fpm
    api_dummy:
        image: elifesciences/api-dummy:${DEPENDENCIES_API_DUMMY}
