version: '3'

services:
    composer:
        volumes:
            - ./composer.json:/app/composer.json
            - ./composer.lock:/app/composer.lock
            - vendor:/app/vendor
    fpm:
        volumes:
            - ./:/srv/recommendations
            - /srv/recommendations/build
            - /srv/recommendations/var
            - .docker/config.php:/srv/recommendations/config.php
            - vendor:/srv/recommendations/vendor
        environment:
            - APP_ENV=${APP_ENV}
        depends_on:
            composer:
                condition: service_completed_successfully
            api_dummy:
                condition: service_healthy
    web:
        depends_on:
            fpm:
                condition: service_healthy
volumes:
    vendor:
