services:
    composer:
        build:
            context: .
            dockerfile: Dockerfile
            target: composer_dev
        command: /bin/bash
        volumes:
            - ./composer.json:/app/composer.json
            - ./composer.lock:/app/composer.lock
            - vendor:/app/vendor
    app:
        build:
            target: dev
        volumes:
            - ./:/app
            - /app/build
            - /app/var
            - .docker/config.php:/app/config.php
            - vendor:/app/vendor
        environment:
            - APP_ENV=${APP_ENV}
        depends_on:
            composer:
                condition: service_completed_successfully
volumes:
    vendor:
