<?php

namespace eLife\App;

use Closure;
use Exception;
use LogicException;
use Psr\Log\LoggerInterface;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;
use Doctrine\DBAL\DriverManager;

final class Console
{
    /**
     * These commands map to [name]Command so when the command "hello" is configured
     * it will call helloCommand() on this class with InputInterface and OutputInterface
     * as parameters.
     *
     * This will hopefully cover most things.
     */
    public static $quick_commands = [
        'hello' => ['description' => 'This is a quick hello world command'],
        'echo' => ['description' => 'Example of asking a question'],
        'cache:clear' => ['description' => 'Clears cache'],
        'debug:params' => ['description' => 'Lists current parameters'],
        'generatedatabase' => ['description' => 'Generates Database'],
    ];

    public function __construct(Application $console, Kernel $app)
    {
        $this->console = $console;
        $this->app = $app;
        $this->root = __DIR__.'/../..';

        $this->console->getDefinition()->addOption(new InputOption('--env', '-e', InputOption::VALUE_REQUIRED, 'The Environment name.', 'dev'));
    }

    private function path($path = '')
    {
        return $this->root.$path;
    }

    public function debugParamsCommand(InputInterface $input, OutputInterface $output, LoggerInterface $logger)
    {
        foreach ($this->app->get('config') as $key => $config) {
            if (is_array($config)) {
                $logger->warning($key);
                $logger->info(json_encode($config, JSON_PRETTY_PRINT));
                $logger->debug(' ');
            } elseif (is_bool($config)) {
                $logger->warning($key);
                $logger->info($config ? 'true' : 'false');
                $logger->debug(' ');
            } else {
                $logger->warning($key);
                $logger->info($config);
                $logger->debug(' ');
            }
        }
    }

    public function cacheClearCommand(InputInterface $input, OutputInterface $output, LoggerInterface $logger)
    {
        $logger->warning('Clearing cache...');
        try {
            exec('rm -rf '.$this->root.'/cache/*');
        } catch (Exception $e) {
            $logger->error($e);
        }
        $logger->info('Cache cleared successfully.');
    }

    public function echoCommand(InputInterface $input, OutputInterface $output, LoggerInterface $logger)
    {
        $question = new Question('<question>Are we there yet?</question> ');
        $helper = new QuestionHelper();
        while (true) {
            $name = $helper->ask($input, $output, $question);
            if ($name === 'yes') {
                break;
            }
            $logger->error($name);
        }
    }

    public function helloCommand(InputInterface $input, OutputInterface $output, LoggerInterface $logger)
    {
        $logger->info('Hello from the outside (of the global scope)');
        $logger->debug('This is working');
    }

    public function generatedatabaseCommand(){

        $conn = DriverManager::getConnection();
            die(var_dump($conn));

        $app = $this->app;
        var_dump($app);
        die;


        $conn = DriverManager::getConnection($params, $config);

        $sql = "-- MySQL Script generated by MySQL Workbench
                -- Wed Dec  7 13:53:59 2016
                -- Model: New Model    Version: 1.0
                -- MySQL Workbench Forward Engineering
                
                SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
                SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
                SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
                
                -- -----------------------------------------------------
                -- Schema recommendations
                -- -----------------------------------------------------
                DROP SCHEMA IF EXISTS `recommendations` ;
                
                -- -----------------------------------------------------
                -- Schema recommendations
                -- -----------------------------------------------------
                CREATE SCHEMA IF NOT EXISTS `recommendations` DEFAULT CHARACTER SET utf8 ;
                USE `recommendations` ;
                
                -- -----------------------------------------------------
                -- Table `recommendations`.`References`
                -- -----------------------------------------------------
                DROP TABLE IF EXISTS `recommendations`.`References` ;
                
                CREATE TABLE IF NOT EXISTS `recommendations`.`References` (
                  `Id1` INT NOT NULL,
                  `Id2` INT NOT NULL,
                  PRIMARY KEY (`Id1`, `Id2`))
                ENGINE = InnoDB;
                
                
                -- -----------------------------------------------------
                -- Table `recommendations`.`RuleModels`
                -- -----------------------------------------------------
                DROP TABLE IF EXISTS `recommendations`.`RuleModels` ;
                
                CREATE TABLE IF NOT EXISTS `recommendations`.`RuleModels` (
                  `Id` INT NOT NULL,
                  `type` VARCHAR(45) NOT NULL,
                  `published` DATETIME NULL,
                  `synthetic` INT NULL,
                  PRIMARY KEY (`Id`, `type`))
                ENGINE = InnoDB;
                
                
                SET SQL_MODE=@OLD_SQL_MODE;
                SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
                SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;";

        $stmt = $conn->query($sql);


    }

    public function run()
    {
        foreach (self::$quick_commands as $name => $cmd) {
            if (strpos($name, ':')) {
                $pieces = explode(':', $name);
                $first = array_shift($pieces);
                $pieces = array_map('ucfirst', $pieces);
                array_unshift($pieces, $first);
                $fn = implode('', $pieces);
            } else {
                $fn = $name;
            }
            if (!method_exists($this, $fn.'Command')) {
                throw new LogicException('Your command does not exist: '.$fn.'Command');
            }
            // Hello
            $command = $this->console
                ->register($name)
                ->setDescription($cmd['description'] ?? $name.' command')
                ->setCode(Closure::bind(function (InputInterface $input, OutputInterface $output) use ($fn, $name) {
                    $logger = new CliLogger($input, $output);
                    $this->{$fn.'Command'}($input, $output, $logger);
                }, $this));

            if (isset($cmd['args'])) {
                foreach ($cmd['args'] as $arg) {
                    $command->addArgument($arg['name'], $arg['mode'] ?? null, $arg['description'] ?? '', $arg['default'] ?? null);
                }
            }
        }
        $this->console->run();
    }
}
